# Generated by Django 5.1.5 on 2025-06-01 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, null=True)),
                ("email", models.EmailField(max_length=150, null=True)),
                ("phone", models.CharField(max_length=150, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GameStick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer", models.CharField(blank=True, max_length=100, null=True)),
                ("model", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("Orginal", "Orginal"), ("copy", "copy")],
                        max_length=150,
                        null=True,
                    ),
                ),
                ("stick_number", models.IntegerField(blank=True, null=True)),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("NEW", "NEW"), ("USED", "USED"), ("OTHER", "OTHER")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("issue", models.CharField(blank=True, max_length=20, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Laptop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "device_type_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("issue", models.TextField(blank=True, null=True)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("processor", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "secondary_hard_drive",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("igc", models.CharField(blank=True, max_length=100, null=True)),
                ("dsgc", models.CharField(blank=True, max_length=100, null=True)),
                ("drive", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "powersupply",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "monitor_serial_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("source", models.CharField(max_length=100)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Item"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Model"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Quantity"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("NEW", "NEW"), ("USED", "USED"), ("OTHER", "OTHER")],
                        max_length=50,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "warranty",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Warranty"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Serial Number",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Source"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "device_type_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("issue", models.TextField(blank=True, null=True)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "motherboard",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("processor", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "secondary_hard_drive",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("igc", models.CharField(blank=True, max_length=100, null=True)),
                ("dsgc", models.CharField(blank=True, max_length=100, null=True)),
                ("drive", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "powersupply",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("case_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cooling_system",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "expansion_slots",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlayStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "device_type_model",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PS2", "PS2"),
                            ("PS2 Slim", "PS2 Slim"),
                            ("PS3", "PS3"),
                            ("PS3 Slim", "PS3 Slim"),
                            ("PS3 Super Slim", "PS3 Super Slim"),
                            ("PS4", "PS4"),
                            ("PS4 Slim", "PS4 Slim"),
                            ("PS4 Pro", "PS4 Pro"),
                            ("PS5", "PS5"),
                            ("PS5 Digital Edition", "PS5 Digital Edition"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("issue", models.TextField(blank=True, null=True)),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("storage", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "power_supply",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "firmware_version",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("accessories", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Router",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer", models.CharField(blank=True, max_length=100, null=True)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(blank=True, max_length=17, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("NEW", "NEW"), ("USED", "USED"), ("OTHER", "OTHER")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("issue", models.CharField(blank=True, max_length=20, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Technician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, null=True)),
                ("email", models.EmailField(max_length=150, null=True)),
                ("phone", models.CharField(max_length=150, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="laptopHARD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hard_type",
                    models.CharField(
                        blank=True,
                        choices=[("SSD", "SSD"), ("HDD", "HDD")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("hard_size", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "hard_serial_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "laptop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hards",
                        to="Maintenance.laptop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="laptopRAM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ram_type", models.CharField(blank=True, max_length=50, null=True)),
                ("ram_size", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "ram_serial_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "laptop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rams",
                        to="Maintenance.laptop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="pcHARD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hard_type",
                    models.CharField(
                        blank=True,
                        choices=[("SSD", "SSD"), ("HDD", "HDD")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("hard_size", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "hard_serial_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "pc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hards",
                        to="Maintenance.pc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="pcRAM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ram_type", models.CharField(blank=True, max_length=50, null=True)),
                ("ram_size", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "ram_serial_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "pc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rams",
                        to="Maintenance.pc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Item"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Model"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Quantity"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
                (
                    "received_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Received Amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("NEW", "NEW"), ("USED", "USED"), ("OTHER", "OTHER")],
                        max_length=50,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "warranty",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Warranty"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Serial Number",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cost",
                    ),
                ),
                (
                    "net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Net",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Maintenance.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Pick a Device"),
                            ("laptop", "Laptop"),
                            ("pc", "PC"),
                            ("playstation", "PlayStation"),
                            ("gamestick", "GameStick"),
                            ("router", "Router"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "customer_phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("issue", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "maintenance_time",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "maintenance_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("maintenance_report", models.TextField(blank=True, null=True)),
                (
                    "maintenance_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("handover_date", models.DateField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Maintenance.customer",
                    ),
                ),
                (
                    "gamestick",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Maintenance.gamestick",
                    ),
                ),
                (
                    "laptop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Maintenance.laptop",
                    ),
                ),
                (
                    "pc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Maintenance.pc",
                    ),
                ),
                (
                    "playstation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Maintenance.playstation",
                    ),
                ),
                (
                    "router",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Maintenance.router",
                    ),
                ),
                (
                    "technician_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Maintenance.technician",
                    ),
                ),
            ],
        ),
    ]
